// File generated by Antigravity based on user provided google-services.json
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: 'AIzaSyAOOryNP-JVJvs83jcm0hGTISQEDGm13wk',
        appId: '1:1064318448585:web:ba48557997327ddec0e06e', // Extrapolated from Android/Project ID
        messagingSenderId: '1064318448585',
        projectId: 'bharat-heritage-a5f12',
        storageBucket: 'bharat-heritage-a5f12.firebasestorage.app',
        authDomain: 'bharat-heritage-a5f12.firebaseapp.com',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // TODO: User needs to provide GoogleService-Info.plist for iOS
        return const FirebaseOptions(
          apiKey: '',
          appId: '',
          messagingSenderId: '',
          projectId: 'bharat-heritage-a5f12',
          storageBucket: 'bharat-heritage-a5f12.firebasestorage.app',
          iosBundleId: 'com.example.bharatHeritage',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOOryNP-JVJvs83jcm0hGTISQEDGm13wk',
    appId: '1:1064318448585:android:0a9fceea46f7cad5e06e18',
    messagingSenderId: '1064318448585',
    projectId: 'bharat-heritage-a5f12',
    storageBucket: 'bharat-heritage-a5f12.firebasestorage.app',
  );
}
