name: Deploy Android App Bundle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run code generation
        run: dart run build_runner build -d

      - name: Run analyzer
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build Android App Bundle
        run: flutter build aab --release
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/bundle/release/app-release.aab
